# Generated by Django 4.2.2 on 2023-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_options_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='not-image.jpg', null=True, upload_to='uploads/'),
        ),
    ]
