# Generated by Django 4.2.2 on 2023-08-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='uploads/not-image.jpg', null=True, upload_to='uploads/'),
        ),
    ]
